const cars = [
  {
    name: "Koenigsegg",
    type: "Sport",
    fuel: "90L",
    transmission: "Manual",
    seats: 2,
    pricePerDay: 99,
  },
  {
    name: "Nissan GT-R",
    type: "Sport",
    fuel: "80L",
    transmission: "Manual",
    seats: 2,
    pricePerDay: 80,
  },
  {
    name: "Rolls-Royce",
    type: "Sedan",
    fuel: "70L",
    transmission: "Manual",
    seats: 4,
    pricePerDay: 96,
  },
  {
    name: "All New Rush",
    type: "SUV",
    fuel: "70L",
    transmission: "Manual",
    seats: 6,
    pricePerDay: 72,
  },
  {
    name: "CR-V",
    type: "SUV",
    fuel: "80L",
    transmission: "Manual",
    seats: 6,
    pricePerDay: 80,
  },
  {
    name: "All New Terios",
    type: "SUV",
    fuel: "90L",
    transmission: "Manual",
    seats: 6,
    pricePerDay: 74,
  },
  {
    name: "MG ZX Exclusive",
    type: "Hatchback",
    fuel: "70L",
    transmission: "Manual",
    seats: 4,
    pricePerDay: 76,
  },
  {
    name: "New MG ZS",
    type: "SUV",
    fuel: "80L",
    transmission: "Manual",
    seats: 6,
    pricePerDay: 80,
  },
  {
    name: "MG ZX Excite",
    type: "Hatchback",
    fuel: "70L",
    transmission: "Manual",
    seats: 4,
    pricePerDay: 74,
  },
];

export default cars;
